### ISSUE TITLE
Basic JavaScript

### ISSUE THREAD

**Issue by alexmandelshtam** [alexownejazayeri/100-days-of-code#29]

**Comment by alexmandelshtam** [comment]
# To-Do

- [x] Comparison with the greater than operator
- [x] Comparison w/ >=
- [x] <
- [x] <=
- [x] &&
- [x] ||
- [x] else
- [x] else if
- [x] if else
- [x] chaining if else
- [x] golf code
- [x] selecting from many options with switch statements
- [x] default option in switch statements
- [x] multiple identical options in switch statements
- [x] replacing if else chains with switch
- [x] returning bools from functions
- [x] return early pattern for functions
- [x] counting cards
- [x] build js objects
- [x] accessing object props with dot notation
- [x] accessing object props with bracket notation
- [x] accessing object props with variables
- [x] updating object props
- [x] add new props to a js obj
- [x] delete props from a js obj
- [x] using obj for lookups
- [x] testing obj for props
- [x] manipulating complex objects
- [x] accessing nested obj
- [x] accessing nested arrays
- [x] record collection
- [x] iterate with js while loops
- [x] iterate with js for loops
- [x] iterate odd numbers with a for loop
- [x] count backwards with a for loop
- [x] iterate through an array with a for loop
- [x] nesting for loops
- [x] iterate with do...while loops
- [x] replace loops using recursion
- [x] profile lookup
- [x] generate random fractions with js
- [x] generate random whole numbers with js
- [x] generate random whole numbers w/in a range
- [x] use parseInt
- [x] use parseInt w/ a Radix
- [x] use conditional (ternary) operator
- [x] use multiple ternary operators
- [x] use recursion to create a countdown
- [x] use recursion to create a range of numbers

**Comment by alexmandelshtam** [comment]
# Topics for review

- record collection: accessing and manipulating objects properties based on conditional statements (if check, etc.)
- short circuit evaluation w/ (&& and ||)
- `do...while` loops
- recursion
- `in` operator
- Math() and understanding floating point inaccuracy
- undefined, null, and details of object data types
- `.find()` method on objects
-  `parseInt()` radix
- style and usage of conditional / ternary operator e.g.(returning null)
