### ISSUE TITLE
ES6

### ISSUE THREAD

**Issue by alexmandelshtam** [alexownejazayeri/100-days-of-code#30]

**Comment by alexmandelshtam** [comment]
# To-do

- [x] compare scoped of the var and let keywords
- [x] mutate an array declared with const
- [x] prevent object mutation
- [x] use arrow functions to write concise anonymous functions
- [x] write arrow functions with parameters
- [x] set default parameters for your functions
- [x] use the rest parameter with function parameters
- [x] use the spread operator to evaluate array in-place
- [x] use destructuring assignment to extract values from objects
- [x] use destructuring assignment to assign variables from objects
- [x] use destructuring assignment to assign variables from nested objects
- [x] use destructuring assignment to assign variables from arrays
- [x] use destructuring assignment to assign with the rest parameter to reassign array elements
- [x] use destructuring assignment to pass an object as a function's paramters
- [x] create strings using template literals
- [x] write concise object literal declarations using object property shorthand
- [x] write concise declarative functions with es6
- [x] use class syntax to define a constructor function
- [x] use getter and setters to control access to an object
- [x] create a module script
- [x] use export to share a code block
- [x] reuse javascript code using import
- [x] use * to import everything from a file
- [x] create an export fallback with export default
- [x] import a default export
- [x] create a javascript promise
- [x] complete a promise with resolve and reject
- [x] handle a fulfilled promise with then
- [x] handle a rejected promise with catch

**Comment by alexmandelshtam** [comment]
# Task Log

## Review
- [ ] Preventing object mutation w/ `Object.freeze()`
- [ ] Default parameters
- [ ] Rest (`...`) parameter
- [ ] `apply()`
- [ ] Use desctructuring assignment with the rest parameter (`...`) to reassign array elements
- [ ] Write concise object literal declarations using object property shorthand
- [ ] write concise declarative functions with es6
- [ ] use class syntax to define a constructor function
- [ ] getters and setters
- [ ] constructor functions
- [ ] promises
