### ISSUE TITLE
Regular Expressions

### ISSUE THREAD

**Issue by alexmandelshtam** [alexownejazayeri/100-days-of-code#31]

**Comment by alexmandelshtam** [comment]
# Todo

- [x] Using the test method
- [x] Match literal strings
- [x] Match literal string with different possibilities
- [x] Ignore case while matching
- [x] Extract matches
- [x] Find more than the first match
- [x] Match anything with wildcard period
- [x] Match single character with multiple possibilities
- [x] Match letters of the alphabet
- [x] Match numbers and letters of the laphabet
- [x] Match single characters not specified
- [x] Match characters that occur one or more times
- [x] Match characters that occur zero or more times
- [x] Find characters with lazy matching
- [x] Find one or more criminals in a hunt
- [x] Match beginning string patterns
- [x] Match ending string patterns
- [x] Match all letters and numbers
- [x] Match everything but letters and numbers
- [x] Match all numbers
- [x] Match all non-numbers
- [x] Restrict possible usernames
- [x] Match whitespace
- [x] Match non-whitespace characters
- [x] Specify upper and lower number of matches
- [x] Specify only the lower number of matches
- [x] Specify exact number of matches
- [x] Check for all or none
- [x] Positive and negative lookahead
- [x] Check for mixed grouping of characters
- [x] Reuse patterns using capture groups
- [x] Use capture groups to search and replace
- [x] Remove whitespace from start and end
