### ISSUE TITLE
Debugging

### ISSUE THREAD

**Issue by alexmandelshtam** [alexownejazayeri/100-days-of-code#32]

**Comment by alexmandelshtam** [comment]
# To-do

- [x] Use JS console to check the value of a variable
- [x] Understanding the difference between the fcc and browser console
- [x] Use `typeof` to check the type of a variable
- [x] Catch misspelled variable and function names
- [x] Catch unclosed parens, brackets, braces, and quotes
- [x] Catch mixed usage of single and double quotes
- [x] Catch use of assignment operator instead of equality operator
- [x] Catch missing open and closing parenthesis after function call
- [x] Catch arguments passed in the wrong order when calling a function
- [x] Catch off by one errors when using indexing
- [x] Use caution when reinitializing variables inside a loop
- [x] Prevent infinite loops with a valid terminal condition
