### ISSUE TITLE
Basic Data Structures

### ISSUE THREAD

**Issue by alexmandelshtam** [alexownejazayeri/100-days-of-code#33]

**Comment by alexmandelshtam** [comment]
# To-do

- [x] Use an array to stoe a collection of data
- [x] Access an array's contents using bracket notation
- [x] Add items into an array with `push()` and `unshift()`
- [x] Remove items from an array with `pop()` and `shift()`
- [x] Remove items using `splice()`
- [x] Add items using `splice()`
- [x] Copy array items using `splice()`
- [x] Copy an array with the spread operator
- [x] Combine arrays with the spread operator
- [x] Check for the presence of an element with `indexOf()`
- [x] Iterate through all an array's items using for loops
- [x] create complex multi-dimensional arrays
- [x] add key-value pairs to js objects
- [x] modify an object nested within an object
- [x] access property names with bracket notation
- [x] use the delete keyword to remove object properties
- [x] check if an object has a property
- [x] iterate through the keys of an object with a for...in statement
- [x] generate an array of all object keys with Object.keys()
- [x] modify an array stored in an object

**Comment by alexmandelshtam** [comment]
# Review later

- [ ] `hasOwnProperty()` vs. `in` keyword for property presence in object
- [ ] `every()` method
- [ ] `for...in` statements for iterating through object keys
- [ ] `Object.keys()`
