### ISSUE TITLE
Basic Algorithm Scripting

### ISSUE THREAD

**Issue by alexmandelshtam** [alexownejazayeri/100-days-of-code#34]

**Comment by alexmandelshtam** [comment]
# Todo

- [x] Convert c to f
- [x] Reverse a string
- [x] Factorialize a number
- [x] Find the longest word in a string
- [x] Return the largest numbers in arrays
- [x] Confirm the ending
- [x] Repeat a string repeat a string
- [x] Truncate a string
- [x] Finders keepers
- [x] Boo who
- [x] Title case a sentence
- [x] Slice and splice
- [x] Falsy bouncer
- [x] Where do I belong
- [x] Mutations
- [x] Chunky Monkey

**Comment by alexmandelshtam** [comment]
# Review

- [ ] `Function.apply` and `Function.apply.bind()` (declarative)
- [ ] `Array.prototype.find()`
- [ ]  Logical OR assignment `||=` and short circuiting
- [ ] `.replace()`
- [ ] `.charAt()`
- [ ] `.substring()`
- [ ] `Boolean` - check [this](https://forum.freecodecamp.org/t/javascript-booleans-explained-how-to-use-booleans-in-javascript/14311) out
- [ ] `.sort()`
