### ISSUE TITLE
Object Oriented Programming

### ISSUE THREAD

**Issue by alexmandelshtam** [alexownejazayeri/100-days-of-code#35]

**Comment by alexmandelshtam** [comment]
# Todo

- [x] Create a basic javascript object
- [x] Use dot notation to access the properties of an object
- [x] Create a method on an object
- [x] Make code more reusable with the `this` keyword
- [x] Define a constructor function
- [x] Use a constructor to create objects
- [x] Extend constructors to receive arguments
- [x] Verify an object's constructor with instanceof
- [x] Understand own properties
- [x] Use prototype properties to reduce duplicate code
- [x] Iterate over all properties
- [x] Understand the constructor property
- [x] Change the prototype to a new object
- [x] Remember to set the constructor property when changing the prototype
- [x] Understand where an object's prototype comes from
- [x] Understand the prototype chain
- [x] Use inheritance (DRY)
- [x] Inherit behaviors from a Supertype
- [x] Set the child's prototype to an instance of the parent
- [x] Reset an inherited constructor property
- [x] Add methods after inheritance
- [x] Override inherited methods
- [x] Use a mixin to add common behavior between unrelated objects
- [x] Use closure to protect properties within an object from being modified externally
- [x] Understand the **Immediately Invoked Function Expression (IIFE)**
- [x] Use an IIFE to create a module

**Comment by alexmandelshtam** [comment]
# Performance

## Date
05/07/22

## Start TIme
6:25PM

## End Time
8:56PM

## Review 

- [ ] `this` keyword
- [ ] constructors and the `constructor` property
- [ ] `new` keyword
- [ ] instances
- [ ] own properties & `Object.hasOwnProperty()`
- [ ] `for...in` statements
- [ ] `prototype` property and `isPrototypeOf()` property
- [ ] Advantages of `Object.create(Supertype.prototype)` notation vs. using the `new` keyword to create instances
- [ ] mixins
- [ ] Immediately Invoked Function Expression (IIFE)
