### ISSUE TITLE
Functional Programming

### ISSUE THREAD

**Issue by alexmandelshtam** [alexownejazayeri/100-days-of-code#36]

**Comment by alexmandelshtam** [comment]
# Todo

- [x] Learn about functional programming
- [x] Understand functional programming terminology
- [x] Understand the hazards of using imperative code
- [x] Avoid mutations and side effects using functional programming
- [x] Pass arguments to avoid external dependence in a function
- [x] Refactor global variables out of functions
- [x] Use the map method to extract data from an array
- [x] Implement map on a prototype
- [x] Use the filter method to extract data from an array
- [x] Implement the filter method on a prototype
- [x] Return part of an array using the slice method
- [x] Remove elements from an array using slice instead of splice
- [x] Combine two arrays using the concat method
- [x] Add elements to the end of an array using concat instead of push
- [x] Use the reduce method to analyze data
- [x] Use higher-order functions map, filter, or reduce to solve a complex problem
- [x] Sort an array alphabetically using the sort method
- [x] Return a sorted array without changing the original
- [x] Split a string into an array using the split method
- [x] Combine an array into a string using the join method
- [x] Apply functional programming to convert strings to URL slugs
- [x] Use the every method to check that every element in an array meets a criteria
- [x] Use the some method to check that any elements in an array meet a criteria
- [x] Introduction to currying and partial application

**Comment by alexmandelshtam** [comment]
# Review

- [ ] callbacks
- [ ] first class and higher order functions
- [ ] lambda function
- [ ] mutation
- [ ] side effects
- [ ] parameter destructuring
- [ ] parens as return statements?

Example
```javascript
const slicedList = watchList.map(({Title: title, imdbRating: rating}) => ({title, rating}));
```

- [ ] `.concat()`
- [ ] `reduce()`
- [ ] `.sort()`
- [ ] `.trim()`
- [ ] arity, currying, and partial application
