### ISSUE TITLE
Intermediate Algorithm Scripting

### ISSUE THREAD

**Issue by alexmandelshtam** [alexownejazayeri/100-days-of-code#37]

**Comment by alexmandelshtam** [comment]
# Todo

- [x] Sum all numbers in a range
- [x] Diff two arrays
- [x] Seek and destroy
- [x] Wherefore art though
- [x] Spinal tap case
- [x] Pig latin
- [x] Search and replace
- [x] DNA pairing
- [x] Missing letters
- [x] Sorted union
- [x] Convert HTML entities
- [ ] Sum all odd fibonacci numbers
- [ ] Sum all primes
- [ ] Smallest common multiple
- [ ] Drop it
- [ ] Steamroller
- [ ] Binary agents
- [ ] Everything be true
- [ ] Arguments optional
- [ ] Make a person
- [ ] Map the debris

**Comment by alexmandelshtam** [comment]
# Review

- [ ] `.charCodeAt()`
- [ ] `.charCodeAt()`
- [ ] `Array.prototype.flat()`
- [ ] Sets
- [ ] IndexOf
