### ISSUE TITLE
Review Functional Programming concepts

### ISSUE THREAD

**Issue by alexmandelshtam** [alexownejazayeri/100-days-of-code#67]
# Review

## To-do

- [x]  callbacks
- [x]  first class and higher order functions
- [x]  lambda function
- [x]  mutation
- [x]  side effects
- [x]  parameter destructuring
- [x]  parens as return statements?

Example: parameter desctructuring and returning an object in parens; arrow function syntax
```javascript
const slicedList = watchList.map(({Title: title, imdbRating: rating}) => ({title, rating}));
```

- [x] .concat()
- [x]  reduce()
- [x]  .sort()
- [x]  .trim()
- [x]  arity, currying, and partial application
