### ISSUE TITLE
[OFFER] Apply to 100 jobs by end of challenge

### ISSUE THREAD

**Issue by alexmandelshtam** [alexownejazayeri/100-days-of-code#69]
# Todo

- [ ] Apply to 4 open positions/day through the end of the challenge
- [ ] A/B test resumes - send 2 x A and 2 x B each day
- [ ] Continue making incremental updates based on TIH

**Comment by alexmandelshtam** [comment]
Got hired at Aloompa!!
